services:
    eliza:
        command: ["pnpm", "start"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - ./characters:/app/characters
        env_file:
            - .env
        ports:
            - "3000:3000"
        restart: always

    postgres:
        image: ankane/pgvector
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres

volumes:
    postgres:
    app:
