# fly.toml app configuration file generated for eliza-sparkling-snowflake-7903 on 2024-11-21T20:27:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eliza-sparkling-snowflake-7903'
primary_region = 'lax'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
